# fly.toml file generated for mattbnz-subscribe on 2023-01-17T00:40:54+13:00

app = "mattbnz-subscribe"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  ML_GROUP = "77434585283036318"
  ALLOWED_REFERERS = "https://www.mattb.nz/,https://mattb.nz/,https://www.mattb.net.nz/,https://mattb.net.nz/"
  HOST = "subscribe.mattb.nz"

[experimental]
  auto_rollback = true

[[services]]
  tcp_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    method = "get"
    path = "/healthz"
    protocol = "http"
